# Base configuration shared between environments
services:
  backend:
    build:
      context: ./
    container_name: dog-breeds-backend
    ports:
      - '${PORT:-3001}:3001'
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    networks:
      - dog-breeds-network
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').request('http://localhost:3001/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1) }).end()",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: dog-breeds-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - dog-breeds-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  favorites_data:
    driver: local
  redis_data:
    driver: local
  node_modules_cache:
    driver: local

networks:
  dog-breeds-network:
    driver: bridge
